/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { assignTaskToProject } from '../fn/task/assign-task-to-project';
import { AssignTaskToProject$Params } from '../fn/task/assign-task-to-project';
import { deleteTask } from '../fn/task/delete-task';
import { DeleteTask$Params } from '../fn/task/delete-task';
import { editTask } from '../fn/task/edit-task';
import { EditTask$Params } from '../fn/task/edit-task';
import { findAllTasks } from '../fn/task/find-all-tasks';
import { FindAllTasks$Params } from '../fn/task/find-all-tasks';
import { findTaskById } from '../fn/task/find-task-by-id';
import { FindTaskById$Params } from '../fn/task/find-task-by-id';
import { PageResponseTaskResponse } from '../models/page-response-task-response';
import { saveTask } from '../fn/task/save-task';
import { SaveTask$Params } from '../fn/task/save-task';
import { TaskResponse } from '../models/task-response';

@Injectable({ providedIn: 'root' })
export class TaskService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `findAllTasks()` */
  static readonly FindAllTasksPath = '/task';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findAllTasks()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllTasks$Response(params?: FindAllTasks$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseTaskResponse>> {
    return findAllTasks(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findAllTasks$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllTasks(params?: FindAllTasks$Params, context?: HttpContext): Observable<PageResponseTaskResponse> {
    return this.findAllTasks$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseTaskResponse>): PageResponseTaskResponse => r.body)
    );
  }

  /** Path part for operation `saveTask()` */
  static readonly SaveTaskPath = '/task';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `saveTask()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveTask$Response(params: SaveTask$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return saveTask(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `saveTask$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveTask(params: SaveTask$Params, context?: HttpContext): Observable<number> {
    return this.saveTask$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `editTask()` */
  static readonly EditTaskPath = '/task/edit-task/{task-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `editTask()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  editTask$Response(params: EditTask$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return editTask(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `editTask$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  editTask(params: EditTask$Params, context?: HttpContext): Observable<number> {
    return this.editTask$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `deleteTask()` */
  static readonly DeleteTaskPath = '/task/delete/{task-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteTask()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteTask$Response(params: DeleteTask$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return deleteTask(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteTask$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteTask(params: DeleteTask$Params, context?: HttpContext): Observable<number> {
    return this.deleteTask$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `assignTaskToProject()` */
  static readonly AssignTaskToProjectPath = '/task/assign/{project-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `assignTaskToProject()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  assignTaskToProject$Response(params: AssignTaskToProject$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return assignTaskToProject(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `assignTaskToProject$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  assignTaskToProject(params: AssignTaskToProject$Params, context?: HttpContext): Observable<number> {
    return this.assignTaskToProject$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `findTaskById()` */
  static readonly FindTaskByIdPath = '/task/{task-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findTaskById()` instead.
   *
   * This method doesn't expect any request body.
   */
  findTaskById$Response(params: FindTaskById$Params, context?: HttpContext): Observable<StrictHttpResponse<TaskResponse>> {
    return findTaskById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findTaskById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findTaskById(params: FindTaskById$Params, context?: HttpContext): Observable<TaskResponse> {
    return this.findTaskById$Response(params, context).pipe(
      map((r: StrictHttpResponse<TaskResponse>): TaskResponse => r.body)
    );
  }

}
