/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CompletedProjectsResponse {
  completed?: boolean;
  description?: string;
  endDate?: string;
  id?: number;
  name?: string;
  ownerName?: string;
}
