/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TaskResponse {
  assignedTo?: string;
  description?: string;
  dueDate?: string;
  id?: number;
  priority?: string;
  projectName?: string;
  taskStatus?: string;
  title?: string;
}
