services:
  mysql:
    container_name: mysql-tmng
    image: mysql:8.0
    environment:
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: task_management_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3307
    volumes:
      - mysql-db:/var/lib/mysql
    networks:
      - spring-task-management
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-tmng
    image: maildev/maildev
    ports:
        - 1080:1080
        - 1025:1025

networks:
    spring-task-management:
        driver: bridge

volumes:
  mysql-db:
    driver: local