/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { NotificationResponse } from '../../models/notification-response';

export interface FindNotificationById$Params {
  'notification-id': number;
}

export function findNotificationById(http: HttpClient, rootUrl: string, params: FindNotificationById$Params, context?: HttpContext): Observable<StrictHttpResponse<NotificationResponse>> {
  const rb = new RequestBuilder(rootUrl, findNotificationById.PATH, 'get');
  if (params) {
    rb.path('notification-id', params['notification-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<NotificationResponse>;
    })
  );
}

findNotificationById.PATH = '/notifications/{notification-id}';
